#!/bin/bash
# LeLamp Startup Script
# Automatically configures audio and runs the agent

set -e

echo "🪔 LeLamp Startup Script"
echo "========================"

# Find USB microphone card number
find_usb_mic() {
    # Look for USB audio device in arecord output
    MIC_CARD=$(arecord -l 2>/dev/null | grep -i "usb\|pnp" | head -1 | sed -n 's/card \([0-9]*\):.*/\1/p')
    
    if [ -z "$MIC_CARD" ]; then
        # Fallback: find any device with capture capability
        MIC_CARD=$(arecord -l 2>/dev/null | grep "card" | head -1 | sed -n 's/card \([0-9]*\):.*/\1/p')
    fi
    
    echo "$MIC_CARD"
}

# Find headphone/speaker card number
find_speaker() {
    # Look for bcm2835 headphones (3.5mm jack)
    SPEAKER_CARD=$(aplay -l 2>/dev/null | grep -i "headphones\|bcm2835" | head -1 | sed -n 's/card \([0-9]*\):.*/\1/p')
    
    if [ -z "$SPEAKER_CARD" ]; then
        SPEAKER_CARD="0"
    fi
    
    echo "$SPEAKER_CARD"
}

# Configure ALSA with rate conversion
configure_alsa() {
    MIC_CARD=$1
    SPEAKER_CARD=$2
    
    echo "📢 Speaker: card $SPEAKER_CARD"
    echo "🎤 Microphone: card $MIC_CARD"
    
    # Create ALSA config with rate conversion for the USB mic
    # This wraps the hardware device and auto-converts sample rates
    cat > ~/.asoundrc << EOF
# Auto-generated by LeLamp startup script
# Rate-converting virtual device for USB mic

# Virtual microphone with rate conversion
pcm.mic_convert {
    type rate
    slave {
        pcm "hw:${MIC_CARD},0"
        rate 44100
    }
}

# Capture device with plug for format conversion
pcm.mic_plug {
    type plug
    slave.pcm "mic_convert"
}

# Default device configuration
pcm.!default {
    type asym
    playback.pcm "plughw:${SPEAKER_CARD},0"
    capture.pcm "mic_plug"
}

ctl.!default {
    type hw
    card ${MIC_CARD}
}
EOF

    echo "✓ ALSA configured with rate conversion: ~/.asoundrc"
}

# Load audio driver if needed
load_audio_driver() {
    if ! lsmod | grep -q snd_bcm2835; then
        echo "Loading bcm2835 audio driver..."
        sudo modprobe snd_bcm2835 2>/dev/null || true
    fi
}

# Main
echo ""
echo "Step 1: Checking audio drivers..."
load_audio_driver

echo ""
echo "Step 2: Detecting audio devices..."
MIC_CARD=$(find_usb_mic)
SPEAKER_CARD=$(find_speaker)

if [ -z "$MIC_CARD" ]; then
    echo "❌ ERROR: No USB microphone found!"
    echo "   Please plug in your USB microphone and try again."
    exit 1
fi

echo ""
echo "Step 3: Configuring ALSA..."
configure_alsa "$MIC_CARD" "$SPEAKER_CARD"

echo ""
echo "Step 4: Testing audio devices..."
# Quick test that devices are accessible
if arecord -D "plughw:${MIC_CARD},0" -d 1 -f S16_LE -r 16000 /dev/null 2>/dev/null; then
    echo "✓ Microphone test passed"
else
    echo "⚠ Microphone test failed (may still work with rate conversion)"
fi

echo ""
echo "Step 5: Starting LeLamp agent..."
echo "================================"
echo ""

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Determine python command
if [ -f ".venv/bin/python" ]; then
    echo "🐍 Using local environment (.venv)"
    PYTHON_CMD=".venv/bin/python"
    
    # Check if running as root
    if [ "$EUID" -eq 0 ]; then
        $PYTHON_CMD main.py console
    else
        sudo -E $PYTHON_CMD main.py console
    fi
else
    echo "⚠️ Local venv not found, falling back to uv run..."
    
    if [ -f ~/.local/bin/uv ]; then
        UV_PATH=~/.local/bin/uv
    elif command -v uv &> /dev/null; then
        UV_PATH=$(which uv)
    else
        echo "❌ ERROR: UV not found. Install with: curl -LsSf https://astral.sh/uv/install.sh | sh"
        exit 1
    fi
    
    # Check if running as root already
    if [ "$EUID" -eq 0 ]; then
        $UV_PATH run main.py console
    else
        sudo -E $UV_PATH run main.py console
    fi
fi
